### ISSUE TITLE
Feature Request: Color Equals Operator Override

### ISSUE THREAD

**Issue by michaelburt-mohawk** [MohawkRaphaelT/game10003-2d-game-template#5]
Allow Color objects to be compared via the equals (==) operator
![image](https://github.com/user-attachments/assets/a4bec0ae-5410-4970-bda3-61c04d3e100a)

**Comment by MohawkRaphaelT** [comment]
Complete in https://github.com/MohawkRaphaelT/game10003-2d-game-template/commit/429c94cd2671fdcc1bebd0d69ed386b11243204e
